version: '3'
services:
  message-service:
    image: message-service:latest

  user-service:
    image: user-service:latest
    command:
      - "--mysql.address=192.168.113.161"

  user-edge-service:
    image: user-edge-service
    links:
      - user-service
      - message-service
    command:
      - "--redis.address=192.168.113.161"

  course-service:
    image: course-service:latest
    links:
      - user-service
    command:
      - "--mysql.address=192.168.113.161"
      - "--zookeeper.address=192.168.1.172"

  course-edge-service:
    image: course-edge-service:latest
    links:
      - user-edge-service
    command:
          - "--zookeeper.address=192.168.1.172"

  api-gateway-zuul:
    image: api-gateway-zuul
    links:
      - user-edge-service
      - course-edge-service
    ports:
      - 8081:8081
