service:
  port: 8111
  name: user-thrift-service
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://localhost/db_user?characterEncoding=utf-8&useSSL=false


mybatis:
  mapper-locations: classpath:mapper/*.xml